### ISSUE TITLE
문서 출력

### ISSUE THREAD

**Issue by baesy0** [75mm-studio/onset-pricing#67]
두 페이지로 출력 되도록 하기
- 가격 정책
- 의뢰 내용

**Comment by baesy0** [comment]
가격정책부분은 출력모드 일 때 `col-sm-n`을 기준으로 보임

**Comment by baesy0** [comment]
https://stackoverflow.com/questions/22199429/bootstrap-grid-for-printing

**Comment by baesy0** [comment]
### @media
https://naradesign.github.io/article/media-query.html

**Comment by baesy0** [comment]
### print 관련 설정하는 법
https://serpiko.tistory.com/614

**Comment by baesy0** [comment]
### 페이지 나누는 법
찾았다!
https://eunyoe.tistory.com/entry/css-print-css-html-프린트-인쇄-화면-개선

**Comment by baesy0** [comment]
### 부트스트랩 기능으로 프린트 될 부분, 안될 부분 나누는 기능
https://getbootstrap.com/docs/4.0/utilities/display/

**Comment by khw7096** [comment]
프린트 나누는 부분은 무지 편리한 듯~!
